-- DB Erstellen
CREATE DATABASE IF NOT EXISTS studyScript;
USE studyScript;

-- Tabelle: User
CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    IsAdmin BOOLEAN NOT NULL DEFAULT FALSE
);

-- Tabelle: Fach
CREATE TABLE IF NOT EXISTS Fach (
    FachID INT AUTO_INCREMENT PRIMARY KEY,
    Fachname VARCHAR(100) NOT NULL,
    Beschreibung TEXT
);

-- Tabelle: Lehrer
CREATE TABLE IF NOT EXISTS Lehrer (
    LehrerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabelle: Aufgabe
CREATE TABLE IF NOT EXISTS Aufgabe (
    AufgabeID INT AUTO_INCREMENT PRIMARY KEY,
    Titel VARCHAR(200) NOT NULL,
    Beschreibung TEXT,
    DueDate DATETIME NOT NULL,
    Finished BOOLEAN NOT NULL DEFAULT FALSE,
    UserID INT NOT NULL,
    FachID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (FachID) REFERENCES Fach(FachID) ON DELETE RESTRICT
);

-- Tabelle: FachLehrer
CREATE TABLE IF NOT EXISTS FachLehrer (
    FachID INT NOT NULL,
    LehrerID INT NOT NULL,
    ZugewiesenAm DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FachID, LehrerID),
    FOREIGN KEY (FachID) REFERENCES Fach(FachID) ON DELETE CASCADE,
    FOREIGN KEY (LehrerID) REFERENCES Lehrer(LehrerID) ON DELETE CASCADE
);